import express from "express";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(express.json());
app.use(cors({
    origin: "*",
    methods: "GET, POST, PUT, DELETE",
    allowedHeaders: "Content-Type",
}));

let myMovies = [
    {
        "id": 1,
        "title": "MUNJYA",
        "year": 2024,
        "rank": 15,
        "rankChange": "+11",
        "Rating": 67,
        "imdb": 6.5,
        "imdbVotes": "21k",
        "backdropImage": "https://images.justwatch.com/backdrop/317639257/s1440/munjha.webp/munjha.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BM2ZkNzRhNDMtNDkzOS00Zjk1LTllZGQtNjIyYTMxNjg1YzkzXkEyXkFqcGc@._V1_QL75_UX480_.jpg",
        "duration": "2h 3min",
        "hightRank": "01",
        "top10Days": "97 Days",
        "top100Days": "114 Days",
        "top1000Days": "121 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "55k",
        "dislikes": 5,
        "watchlistText": "WatchList",
        "seenText": "Seen",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "qGb5aKEYR8Q"
    },
    {
        "id": 2,
        "title": "STANGER THINGS",
        "year": 2016,
        "rank": 82,
        "rankChange": "+67",
        "Rating": 15,
        "imdb": 8.7,
        "imdbVotes": "1m",
        "backdropImage": "https://images.justwatch.com/backdrop/102141616/s1440/stranger-things.webp/stranger-things.webp",
        "posterImage": "https://rukminim2.flixcart.com/image/850/1000/jr3t5e80/poster/a/w/f/medium-stranger-things-poster-for-room-office-13-inch-x-19-inch-original-imafcww8v99r4qhh.jpeg?q=20&crop=false",
        "duration": "1h 1min",
        "hightRank": "01",
        "top10Days": "228 Days",
        "top100Days": "1921 Days",
        "top1000Days": "2994 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "79k",
        "dislikes": 3.6,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",  
        "videoId" : "b9EkMc79ZSU"
    },
    {
        "id": 3,
        "title": "JUJUTSU KAISEN",
        "year": 2020,
        "rank": 175.,
        "rankChange": "+21",
        "Rating": "93%",
        "imdb": 8.6,
        "imdbVotes": "131K",
        "backdropImage": "https://images.justwatch.com/backdrop/297814126/s1440/jujutsu-kaisen.webp/jujutsu-kaisen.webp",
        "posterImage": "https://i.pinimg.com/originals/ac/43/52/ac4352f877cd4265d69538bd7532b7b3.jpg",
        "duration": " 24min",
        "hightRank": "02",
        "top10Days": "71 Days",
        "top100Days": "390 Days",
        "top1000Days": "1437 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "7.5K",
        "dislikes": 511,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",  
        "videoId" : "Pm-wNmS9RGI"
    },
    {
        "id": 4,
        "title": "STREE 2: SARKATE KA AATANK",
        "year": 2024,
        "rank": "79",
        "rankChange": "+67",
        "Rating": 15,
        "imdb": 7.6,
        "imdbVotes": "25K",
        "backdropImage": "https://images.justwatch.com/backdrop/319090905/s1440/stree-2.webp/stree-2.webp",
        "posterImage": "https://cdn.cinematerial.com/p/297x/suglhbwb/stree-2-indian-movie-poster-md.jpg?v=1721223530",
        "duration": "2h 27min",
        "hightRank": "01",
        "top10Days": "228 Days",
        "top100Days": "1921 Days",
        "top1000Days": "2994 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "79k",
        "dislikes": 3.6,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "hrNF3Qerxrk"
    },
    {
        "id": 5,
        "title": "GOBLIN",
        "year": 2016,
        "rank": 640.,
        "rankChange": "+564",
        "Rating": "73%",
        "imdb": 8.6,
        "imdbVotes": "30k",
        "backdropImage": "https://images.justwatch.com/backdrop/31621283/s1440/goblin.webp/goblin.webp",
        "posterImage": "https://i.pinimg.com/736x/4e/70/9c/4e709c0df244780689bb3ab3d0373b06.jpg",
        "duration": "53min",
        "hightRank": "14",
        "top10Days": "0 Days",
        "top100Days": "286 Days",
        "top1000Days": "1342 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "79k",
        "dislikes": 3.6,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "qXCxYfV6V6c"
    },
    {
        "id": 6,
        "title": "SANAM TERI KASAM",
        "year": 2016,
        "rank": 214,
        "rankChange": "+8",
        "Rating": "69%",
        "imdb": 7.6,
        "imdbVotes": "17k",
        "backdropImage": "https://images.justwatch.com/backdrop/198570000/s1440/sanam-teri-kasam.webp/sanam-teri-kasam.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BYTJmYmI0YWQtYjI3MC00MWU4LWI2OTQtNDYyOGEyNThjZjg3XkEyXkFqcGc@._V1_.jpg",
        "duration": "2h 34min",
        "hightRank": "07",
        "top10Days": "3 Days",
        "top100Days": "117 Days",
        "top1000Days": "1869 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "118k",
        "dislikes": 37,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "_7L9F99K-kM"
    },
    {
        "id": 7,
        "title": "WEDNESDAY",
        "year": 2022,
        "rank": 172,
        "rankChange": "-104",
        "Rating": "95%",
        "imdb": 8.1,
        "imdbVotes": "383K",
        "backdropImage": "https://images.justwatch.com/backdrop/301994024/s1440/wednesday.webp/wednesday.webp",
        "posterImage": "https://c4.wallpaperflare.com/wallpaper/462/216/45/movies-dark-wednesday-addams-wednesday-tv-series-movie-poster-hd-wallpaper-preview.jpg",
        "duration": "29min",
        "hightRank": "01",
        "top10Days": "107 Days",
        "top100Days": "329 Days",
        "top1000Days": "783 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "44k",
        "dislikes": 2.2,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "DwvQLVAxiKY"
    },
    {
        "id": 8,
        "title": "MY FAULT",
        "year": 2023,
        "rank": 579,
        "rankChange": "+453",
        "Rating": "82%",
        "imdb": 6.2,
        "imdbVotes": "28K",
        "backdropImage": "https://images.justwatch.com/backdrop/305772264/s1440/culpa-mia.webp/culpa-mia.webp",
        "posterImage": "https://image.tmdb.org/t/p/original/w46Vw536HwNnEzOa7J24YH9DPRS.jpg",
        "duration": "1h 57min",
        "hightRank": "03",
        "top10Days": "17 Days",
        "top100Days": "82 Days",
        "top1000Days": "484 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "30k",
        "dislikes": 536,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "e7lvpm13ZN0"
    },
    {
        "id": 9,
        "title": "YOUR NAME",
        "year": 2016,
        "rank": "96%",
        "rankChange": "+33",
        "Rating": 15,
        "imdb": 8.4,
        "imdbVotes": "334K",
        "backdropImage": "https://images.justwatch.com/backdrop/56668328/s1440/your-name.webp/your-name.webp",
        "posterImage": "https://wallpapers.com/images/hd/makoto-shinkai-your-name-poster-yd4rjkxb6z58fxgs.jpg",
        "duration": "1h 49min",
        "hightRank": "01",
        "top10Days": "228 Days",
        "top100Days": "1921 Days",
        "top1000Days": "2994 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "30k",
        "dislikes": 382,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "_oWzYOwXn-o"
    },
    {
        "id": 10,
        "title": "SUZUME",
        "year": 2022,
        "rank": 82,
        "rankChange": "+67",
        "Rating": "91%",
        "imdb": 7.6,
        "imdbVotes": "46K",
        "backdropImage": "https://images.justwatch.com/backdrop/306324717/s1440/suzume-no-tojimari.webp/suzume-no-tojimari.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BODhkNDhmNzktODFmMC00NDZiLWEzN2UtY2YwYzgzYTVlMWZmXkEyXkFqcGc@._V1_.jpg",
        "duration": "2h 1min",
        "hightRank": "02",
        "top10Days": "245 Days",
        "top100Days": "1451 Days",
        "top1000Days": "1584 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "2k",
        "dislikes": 263,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "ciQc8lfvSm0",
    },
    {
        "id": 11,
        "title": "MONEY HEIST",
        "year": 2017,
        "rank": 40.,
        "rankChange": "+1",
        "Rating": "91%",
        "imdb": 8.2,
        "imdbVotes": "547k",
        "backdropImage": "https://images.justwatch.com/backdrop/242778527/s1440/paperhouse.webp/paperhouse.webp",
        "posterImage": "https://i.pinimg.com/564x/ae/a2/12/aea212575572799476430c0f1f9550a0.jpg",
        "duration": "50min",
        "hightRank": "01",
        "top10Days": "239 Days",
        "top100Days": "2007 Days",
        "top1000Days": "2481 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "40k",
        "dislikes": "2.7k",
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "8QkyLqmJCMM",
    },
    {
        "id": 12,
        "title": "TUMBBAD",
        "year": 2018,
        "rank": 73,
        "rankChange": "+67",
        "Rating": "82%",
        "imdb": 8.2,
        "imdbVotes": "64k",
        "backdropImage": "https://images.justwatch.com/backdrop/245230559/s1440/tumbbad.webp/tumbbad.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BMzVjNGFmZTMtYjRjNi00OWQzLTlkNWQtZmU1OGI0ODc2ODU5XkEyXkFqcGc@._V1_QL75_UX820_.jpg",
        "duration": "1h 53min",
        "hightRank": "02",
        "top10Days": "258 Days",
        "top100Days": "1458 Days",
        "top1000Days": "2586 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "18k",
        "dislikes": 3.5,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "YGIcZrUBY0k",
    },
    {
        "id": 13,
        "title": "PUT YOUR HEAD ON MY SHOULDER",
        "year": 2019,
        "rank": 1411,
        "rankChange": "+820",
        "Rating": "53%",
        "imdb": 8.0,
        "imdbVotes": "3.4k",
        "backdropImage": "https://images.justwatch.com/backdrop/150332384/s1440/put-your-head-on-my-shoulder.webp/put-your-head-on-my-shoulder.webp",
        "posterImage": "https://wallpapercave.com/wp/wp4935200.jpg",
        "duration": "41min",
        "hightRank": "51",
        "top10Days": "0 Days",
        "top100Days": "5 Days",
        "top1000Days": "239 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "5k",
        "dislikes": 34,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "HMLeGMSeJVM"
    },
    {
        "id": 14,
        "title": "LAILA MAJNU",
        "year": 2018,
        "rank": 12.,
        "rankChange": "+11",
        "Rating": "78%",
        "imdb": 7.7,
        "imdbVotes": "6.6",
        "backdropImage": "https://images.justwatch.com/backdrop/81338817/s1440/laila-majnu.webp/laila-majnu.webp",
        "posterImage": "https://i.pinimg.com/originals/f4/b5/7c/f4b57c6ee3adc7861447e9eb6f0c1739.jpg",
        "duration": "2h 19min",
        "hightRank": "02",
        "top10Days": "8 Days",
        "top100Days": "83 Days",
        "top1000Days": "445 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "55k",
        "dislikes": 358,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "Cv-6cAHanZ8"
    },
    {
        "id": 15,
        "title": "ATTACK ON TITAN",
        "year": 2013,
        "rank": 46.,
        "rankChange": "+63",
        "Rating": "91%",
        "imdb": 9.1,
        "imdbVotes": "546k",
        "backdropImage": "https://images.justwatch.com/backdrop/302212233/s1440/attack-on-titan.webp/attack-on-titan.webp",
        "posterImage": "https://m.media-amazon.com/images/I/817nGTgaEBL.jpg",
        "duration": "25min",
        "hightRank": "01",
        "top10Days": "63 Days",
        "top100Days": "1077 Days",
        "top1000Days": "2941 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "17k",
        "dislikes": "1.6k",
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "LV-nazLVmgo"
    },
    {
        "id": 16,
        "title": "ANIMAL",
        "year": 2023,
        "rank": 192.,
        "rankChange": "+342",
        "Rating": "67%",
        "imdb": 6.1,
        "imdbVotes": "99k",
        "backdropImage": "https://images.justwatch.com/backdrop/309854144/s1440/animal-2022.webp/animal-2022.webp",
        "posterImage": "https://stat4.bollywoodhungama.in/wp-content/uploads/2023/01/Animal.jpg",
        "duration": "1h 1min",
        "hightRank": "01",
        "top10Days": "113 Days",
        "top100Days": "241 Days",
        "top1000Days": "336 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "12k",
        "dislikes": 152,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "Dydmpfo68DA"
    },
    {
        "id": 17,
        "title": "LOVE IS SWEET",
        "year": 2020,
        "rank": 82,
        "rankChange": "+67",
        "Rating": "68",
        "imdb": 8.7,
        "imdbVotes": "18k",
        "backdropImage": "https://images.justwatch.com/backdrop/305955903/s1440/love-is-sweet.webp/love-is-sweet.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BYWZiZTQ0ZTMtOTJhNC00NzIzLTlmNjgtZmRmZDc4NTVmNjlmXkEyXkFqcGc@._V1_.jpg",
        "duration": "44min",
        "hightRank": "03",
        "top10Days": "15 Days",
        "top100Days": "152 Days",
        "top1000Days": "1025 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "10k",
        "dislikes": "1.1k",
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "44SPxWJ9Rno" 
    },
    {
        "id": 18,
        "title": "THE CONJURING",
        "year": 2013,
        "rank": 289.,
        "rankChange": "+207",
        "Rating": "94%",
        "imdb": 7.5,
        "imdbVotes": "564k",
        "backdropImage": "https://images.justwatch.com/backdrop/180456158/s1440/the-conjuring.webp/the-conjuring.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_.jpg",
        "duration": "1h 53min",
        "hightRank": "02",
        "top10Days": "2 Days",
        "top100Days": "117 Days",
        "top1000Days": "2994 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "17k",
        "dislikes": "1.1k",
        "watchlistText": "WatchLists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "ejMMn0t58Lc"
    },
    {
        "id": 19,
        "title": "THE KISSING BOOTH",
        "year": 2018,
        "rank": 3023.,
        "rankChange": "+2225",
        "Rating": "75%",
        "imdb": 5.9,
        "imdbVotes": "96k",
        "backdropImage": "https://images.justwatch.com/backdrop/238965629/s1440/the-kissing-booth.webp/the-kissing-booth.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BNjQ0Mzk0OTE5MF5BMl5BanBnXkFtZTgwNDkyOTI0NTM@._V1_.jpg",
        "duration": "1h 45min",
        "hightRank": "04",
        "top10Days": "13 Days",
        "top100Days": "164 Days",
        "top1000Days": "667 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "4.7k",
        "dislikes": "1.5k",
        "watchlistText": "WatchLists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "7bfS6seiLhk"
    },
    {
        "id": 20,
        "title": "MY GIRLFRIEND IS AN ALIAN",
        "year": 2019,
        "rank": 12,
        "rankChange": "+45",
        "Rating": "76%",
        "imdb": 8.2,
        "imdbVotes": "2.7k",
        "backdropImage": "https://images.justwatch.com/backdrop/300784304/s1440/my-girlfriend-is-an-alien.webp/my-girlfriend-is-an-alien.webp",
        "posterImage": "https://image.tmdb.org/t/p/original/sOtUZ34xeQiEZh6n0tC8vkaTNQF.jpg",
        "duration": "44min",
        "hightRank": "05",
        "top10Days": "425 Days",
        "top100Days": "1451 Days",
        "top1000Days": "2524 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "4k",
        "dislikes": 35,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "m21MWq6wb9Y"
    },
    {
        "id": 21,
        "title": "SHAITAAN",
        "year": 2024,
        "rank": 1841,
        "rankChange": "-650",
        "Rating": "53%",
        "imdb": 6.6,
        "imdbVotes": "51k",
        "backdropImage": "https://images.justwatch.com/backdrop/315476071/s1440/black-magic-2024.webp/black-magic-2024.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BOTdlZGE5YmUtZDE1Ny00NzUzLTg2YzYtNWYyMzgyNzRiY2EzXkEyXkFqcGc@._V1_.jpg",
        "duration": "2h 12min",
        "hightRank": "01",
        "top10Days": "17 Days",
        "top100Days": "105 Days",
        "top1000Days": "208 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "990",
        "dislikes": 112,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "upDhKSx7P7E"
    },
    {
        "id": 22,
        "title": "Bad Newz",
        "year": 2024,
        "rank": 61,
        "rankChange": "-17",
        "Rating": "27%",
        "imdb": 5.1,
        "imdbVotes": "25k",
        "backdropImage": "https://images.justwatch.com/backdrop/321215960/s1440/untitled-vicky-kaushal-prime-video-project.webp/untitled-vicky-kaushal-prime-video-project.webp",
        "posterImage": "https://i.redd.it/posters-of-bad-newz-v0-0343zk5ao4pc1.jpg?width=1290&format=pjpg&auto=webp&s=e452143fc253c376c29205b1b3ae43afb4cf8443",
        "duration": "2h 20min",
        "hightRank": "03",
        "top10Days": "9 Days",
        "top100Days": "41 Days",
        "top1000Days": "80 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "1.5k",
        "dislikes": 203,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
         "videoId" : "uV50UfcIT68"
    },
    {
        "id": 23,
        "title": "NO GAIN NO LOVE",
        "year": 2024,
        "rank": 24,
        "rankChange": "+12",
        "Rating": "53%",
        "imdb": 7.9,
        "imdbVotes": "1.1k",
        "backdropImage": "https://images.justwatch.com/backdrop/320106640/s1440/no-gain-no-love.webp/no-gain-no-love.webp",
        "posterImage": "https://asianwiki.com/images/6/68/No_Gain_No_Love-mp01.jpeg",
        "duration": "1h 8min",
        "hightRank": "12",
        "top10Days": "0 Days",
        "top100Days": "27 Days",
        "top1000Days": "41 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "520",
        "dislikes": 45,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
         "videoId" : "NL88DKtfrl"
    },
    {
        "id": 24,
        "title": "DEMON SLAYER",
        "year": 2019,
        "rank": 29,
        "rankChange": "+6",
        "Rating": "90%",
        "imdb": 8.6,
        "imdbVotes": "166k",
        "backdropImage": "https://images.justwatch.com/backdrop/317220005/s1440/demon-slayer-kimetsu-no-yaiba.webp/demon-slayer-kimetsu-no-yaiba.webp",
        "posterImage": "https://i.pinimg.com/736x/51/2c/9a/512c9a9bfd71ae7ab6b583dca74c318f.jpg",
        "duration": "26min",
        "hightRank": "01",
        "top10Days": "126 Days",
        "top100Days": "660 Days",
        "top1000Days": "1920 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "15k",
        "dislikes": 951,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "VQGCKyvzIM4"
    },
    {
        "id": 25,
        "title": "FRIENDS",
        "year": 1994,
        "rank": 31,
        "rankChange": "+85",
        "Rating": "92%",
        "imdb": 8.9,
        "imdbVotes": "1m",
        "backdropImage": "https://images.justwatch.com/backdrop/177294826/s1440/friends.webp/friends.webp",
        "posterImage": "https://i.pinimg.com/originals/41/2c/ea/412cea60bab9c59e1d7414616d426f81.jpg",
        "duration": "25min",
        "hightRank": "01",
        "top10Days": "869 Days",
        "top100Days": "2581 Days",
        "top1000Days": "3197 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "35k",
        "dislikes": 274,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
         "videoId" : "VQGCKyvzIM4"
    },
    {
        "id": 26,
        "title": "FLAMES",
        "year": 2018,
        "rank": 196,
        "rankChange": "+297",
        "Rating": "71%",
        "imdb": 8.8,
        "imdbVotes": "33k",
        "backdropImage": "https://images.justwatch.com/backdrop/163344875/s1440/flames.webp/flames.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BOTQ5MWNkMDgtNjk5ZC00NGE5LWEyMGQtN2YzNzlkZTgxZWFlXkEyXkFqcGc@._V1_.jpg",
        "duration": "31min",
        "hightRank": "01",
        "top10Days": "71 Days",
        "top100Days": "515 Days",
        "top1000Days": "1793 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "4k",
        "dislikes": 35,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "NkdCgjqQq7s"
    },
    {
        "id": 27,
        "title": "ALICE IN BORDERLAND",
        "year": 2020,
        "rank": 204,
        "rankChange": "+347",
        "Rating": "92%",
        "imdb": 7.7,
        "imdbVotes": "102k",
        "backdropImage": "https://images.justwatch.com/backdrop/239548970/s1440/alice-in-borderland.webp/alice-in-borderland.webp",
        "posterImage": "https://c8.alamy.com/comp/2NT31X7/alice-in-borderland-poster-2NT31X7.jpg",
        "duration": "54min",
        "hightRank": "04",
        "top10Days": "14 Days",
        "top100Days": "152 Days",
        "top1000Days": "1287 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "12k",
        "dislikes": "1k",
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
        "videoId" : "49_44FFKZ1M"
    },
    {
        "id": 28,
        "title": "DARLING IN THE FRANXX",
        "year": 2018,
        "rank": 2599.,
        "rankChange": "+2391",
        "Rating": "85%",
        "imdb": 7.3,
        "imdbVotes": "15k",
        "backdropImage": "https://images.justwatch.com/backdrop/104372012/s1440/darling-in-the-franxx.webp/darling-in-the-franxx.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BYWNlYzk1NGQtNTZkNi00YzJiLWJkMWUtZTYzNjI3YTc5ZDRhXkEyXkFqcGc@._V1_.jpg",
        "duration": "24min",
        "hightRank": "113",
        "top10Days": "458 Days",
        "top100Days": "1458 Days",
        "top1000Days": "1258 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "25k",
        "dislikes": 354,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "xiNeXCUosSg"
    },
    {
        "id": 29,
        "title": "INDORI ISHQ",
        "year": 2021,
        "rank": 45,
        "rankChange": "+451",
        "Rating": "82%",
        "imdb": 6.9,
        "imdbVotes": "4.3k",
        "backdropImage": "https://images.justwatch.com/backdrop/246833725/s1440/indori-ishq.webp/indori-ishq.webp",
        "posterImage": "https://m.media-amazon.com/images/M/MV5BZjJlMTNiYjItMTgxYy00YjRlLTg0NGItYjY1MWNlMGZhNWNmXkEyXkFqcGc@._V1_.jpg",
        "duration": "29min",
        "hightRank": "05",
        "top10Days": "425 Days",
        "top100Days": "1451 Days",
        "top1000Days": "2524 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "4k",
        "dislikes": 35,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List", 
         "videoId" : "SPDL_1e4160"
    },
    {
        "id": 30,
        "title": "EVIL DEAD RISE",
        "year": 2023,
        "rank": 78,
        "rankChange": "+640",
        "Rating": "81%",
        "imdb": 6.5,
        "imdbVotes": "146k",
        "backdropImage": "https://images.justwatch.com/backdrop/305192753/s1440/evil-dead-rise.webp/evil-dead-rise.webp",
        "posterImage": "https://sportshub.cbsistatic.com/i/2023/01/03/732d9bb0-00b5-42b0-86c9-87e7928c9f9c/evil-dead-rise-poster-2022.jpg?auto=webp&width=1382&height=2048&crop=0.675:1,smart",
        "duration": "1h 36min",
        "hightRank": "03",
        "top10Days": "12 Days",
        "top100Days": "126 Days",
        "top1000Days": "549 Days",
        "watchOptions": [
      {"platform": "Netflix", "price": "Rs200/-"},
      {"platform": "Amazon Prime", "price": "Rs500/-"}
    ],
        "likes": "6.1k",
        "dislikes": 452,
        "watchlistText": "Lists",
        "seenText": "Seen all",
        "syncText": "Sign in to sync Watch List",
        "videoId" : "smTK_AeAPHs"
    },
    {
      "id": 31,
      "title": "NARUTO",
      "year": 2002,
      "rank": 34,
      "rankChange": "+82",
      "Rating": "88%",
      "imdb": 8.4,
      "imdbVotes": "134k",
      "backdropImage": "https://images.justwatch.com/backdrop/304968809/s1440/naruto.webp/naruto.webp",
      "posterImage": "https://i.pinimg.com/originals/f8/6c/c3/f86cc358c2f65afc5cc2472f9ec2bcc4.jpg",
      "duration": "23min",
      "hightRank": "06",
      "top10Days": "25 Days",
      "top100Days": "666 Days",
      "top1000Days": "2673 Days",
      "watchOptions": [
    {"platform": "Netflix", "price": "Rs200/-"},
    {"platform": "Amazon Prime", "price": "Rs500/-"}
  ],
      "likes": "8.8k",
      "dislikes": "1k",
      "watchlistText": "Lists",
      "seenText": "Seen all",
      "syncText": "Sign in to sync Watch List",
      "videoId" : "-G9BqkgZXRA"
  },
  {
    "id": 32,
    "title": "LOVE NEXT DOOR",
    "year": 2024,
    "rank": 67.,
    "rankChange": "+19",
    "Rating": "48%",
    "imdb": 8.0,
    "imdbVotes": "2.4k",
    "backdropImage": "https://images.justwatch.com/backdrop/319496696/s1440/moms-friends-son.webp/moms-friends-son.webp",
    "posterImage": "https://0.soompi.io/wp-content/uploads/2024/09/02200901/love-next-door-1.jpg",
    "duration": "1h 20min",
    "hightRank": "07",
    "top10Days": "1 Days",
    "top100Days": "33 Days",
    "top1000Days": "55 Days",
    "watchOptions": [
  {"platform": "Netflix", "price": "Rs200/-"},
  {"platform": "Amazon Prime", "price": "Rs500/-"}
],
    "likes": "6.6k",
    "dislikes": 458,
    "watchlistText": "Lists",
    "seenText": "Seen all",
    "syncText": "Sign in to sync Watch List",
    "videoId" : "C3TpiZndAOo"
},
{
  "id": 33,
  "title": "Gyeongseong Creature",
  "year": 2023,
  "rank": 59.,
  "rankChange": "+59",
  "Rating": "75%",
  "imdb": 7.3,
  "imdbVotes": "13k",
  "backdropImage": "https://images.justwatch.com/backdrop/309788226/s1440/gyeongseong-creature.webp/gyeongseong-creature.webp",
  "posterImage": "https://m.media-amazon.com/images/M/MV5BMWI1N2I5ZGQtNTFkMC00MjIxLTgxNTQtZTgzNDU2YjhkN2JkXkEyXkFqcGc@._V1_.jpg",
  "duration": "1h 1min",
  "hightRank": "0",
  "top10Days": "07 Days",
  "top100Days": "25 Days",
  "top1000Days": "245 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "1k",
  "dislikes": 52,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "Q3YgWMxaq8o"
},
{
  "id": 34,
  "title": "HIDDEN LOVE",
  "year": 2023,
  "rank": 112,
  "rankChange": "+78",
  "Rating": "61%",
  "imdb": "",
  "imdbVotes": "",
  "backdropImage": "https://images.justwatch.com/backdrop/306853997/s1440/hidden-love.webp/hidden-love.webp",
  "posterImage": "https://m.media-amazon.com/images/M/MV5BZTc3MmQ1YjctYWM4YS00YzFmLTg2YjQtNjEzODQ5ZWVjZjVmXkEyXkFqcGc@._V1_.jpg",
  "duration": "45min",
  "hightRank": "03",
  "top10Days": "03 Days",
  "top100Days": "79 Days",
  "top1000Days": "469 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "6k",
  "dislikes": 682,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "SDdbyi6B-IQ"
},
{
  "id": 35,
  "title": "THE GARDEN OF WORDS",
  "year": 2013,
  "rank": "88%",
  "rankChange": "+55",
  "Rating": "45",
  "imdb": 7.5,
  "imdbVotes": "47k",
  "backdropImage": "https://images.justwatch.com/backdrop/315433074/s1440/the-garden-of-words.webp/the-garden-of-words.webp",
  "posterImage": "https://m.media-amazon.com/images/M/MV5BYjdiMDdlMDItOGM4Ny00YmE4LTk0MTEtMGRhM2Y4OWZkZDZkXkEyXkFqcGc@._V1_.jpg",
  "duration": "46min",
  "hightRank": "04",
  "top10Days": "55 Days",
  "top100Days": "452 Days",
  "top1000Days": "1025 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "45k",
  "dislikes": 152,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "2IlccH4VzQ4"
},
{
  "id": 36,
  "title": "COLLEGE ROMANCE",
  "year": 2018,
  "rank": 126.,
  "rankChange": "+160",
  "Rating": "76%",
  "imdb": 8.8,
  "imdbVotes": "29k",
  "backdropImage": "https://images.justwatch.com/backdrop/307434339/s1440/college-romance.webp/college-romance.webp",
  "posterImage": "https://i.pinimg.com/564x/d0/c1/e1/d0c1e10e7280d7be14a8eb0279fbed4a.jpg",
  "duration": "31min",
  "hightRank": "01",
  "top10Days": "309 Days",
  "top100Days": "992 Days",
  "top1000Days": "1622 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "72k",
  "dislikes": 158,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "zwRhlzrJGxo"
},
{
  "id": 37,
  "title": "HEIRS",
  "year": 2017,
  "rank": 45,
  "rankChange": "+12",
  "Rating": "45%",
  "imdb": 6.5,
  "imdbVotes": "36k",
  "backdropImage": "https://images.justwatch.com/backdrop/303444210/s1440/.webp.webp",
  "posterImage": "https://i.pinimg.com/originals/ab/33/b9/ab33b9db9788da8f57f116a517fa713f.jpg",
  "duration": "45min",
  "hightRank": "08",
  "top10Days": "45 Days",
  "top100Days": "458 Days",
  "top1000Days": "1231 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "458",
  "dislikes": 92,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "Y0WSF5ikpvU"
},
{
  "id": 38,
  "title": "5 CENTIMETRE PER SECONDS",
  "year": 2007,
  "rank": 45,
  "rankChange": "+40",
  "Rating": "69%",
  "imdb": 7.5,
  "imdbVotes": "65k",
  "backdropImage": "https://c4.wallpaperflare.com/wallpaper/826/590/471/anime-5-centimeters-per-second-makoto-shinkai-train-wallpaper-preview.jpg",
  "posterImage": "https://m.media-amazon.com/images/M/MV5BMTI4MDIyNzQyNl5BMl5BanBnXkFtZTcwNDcyNTk2MQ@@._V1_.jpg",
  "duration": "1h 3min",
  "hightRank": "03",
  "top10Days": "20 Days",
  "top100Days": "152 Days",
  "top1000Days": "690 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "6.2k",
  "dislikes": 125,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "wdM7athAem0"
},
{
  "id": 39,
  "title": "ALL OF US ARE DEAD",
  "year": 2022,
  "rank": 177,
  "rankChange": "-83",
  "Rating": "88%",
  "imdb": 7.5,
  "imdbVotes": "71k",
  "backdropImage": "https://wallpapers.com/images/featured/all-of-us-are-dead-kckh95o0iza3codt.jpg",
  "posterImage": "https://lh3.googleusercontent.com/QXOt-OYAsmiSttvpL80-83zT30UnSUPolyxlL7VntZi7N9Mu6VfvSd8PukAUzfM9rAedaGmgkWGr5-j7UBwiH-dw5no0HPlWc7leNdoeevlbMdpA=nu-e365-rj-q80-w925",
  "duration": "1h 1min",
  "hightRank": "02",
  "top10Days": "37 Days",
  "top100Days": "290 Days",
  "top1000Days": "1002 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "6.1k",
  "dislikes": 490,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "IN5TD4VRcSM"
},
{
  "id": 40,
  "title": "SILENT VOICE",
  "year": 2016,
  "rank": 81.,
  "rankChange": "+55",
  "Rating": "93%",
  "imdb": 8.1,
  "imdbVotes": "107k",
  "backdropImage": "https://m.media-amazon.com/images/I/81D7Im1raIL._AC_UF350,350_QL80_.jpg",
  "posterImage": "https://m.media-amazon.com/images/I/71Pfz2S9ZQL._AC_UF1000,1000_QL80_.jpg",
  "duration": "2h 9min",
  "hightRank": "05",
  "top10Days": "121 Days",
  "top100Days": "115 Days",
  "top1000Days": "578 Days",
  "watchOptions": [
{"platform": "Netflix", "price": "Rs200/-"},
{"platform": "Amazon Prime", "price": "Rs500/-"}
],
  "likes": "158",
  "dislikes": 45,
  "watchlistText": "Lists",
  "seenText": "Seen all",
  "syncText": "Sign in to sync Watch List",
  "videoId" : "nfK6UgLra7g"
},
 
];

// Find movie by title
app.get('/api/Popular-movies', (req, res) => {
    const titleQuery = req.query.title ? req.query.title.toLowerCase() : null;
    if (titleQuery) {
        const movieByTitle = myMovies.find(movie => movie.title.toLowerCase() === titleQuery);
        if (movieByTitle) {
            return res.json(movieByTitle);
        } else {
            return res.status(404).json({ message: "Movie not found by Title" });
        }
    } else {
        return res.json(myMovies);
    }
});

// Find movie by ID
app.get('/api/Popular-movies/:id', (req, res) => {
    const id = req.params.id;
    const movie = myMovies.find(movie => movie.id === parseInt(id));
    if (!movie) {
        return res.status(404).json({ message: "Movie not found by ID" });
    }
    res.json(movie);
});

// For creating data
app.post('/api/MyMovies', (req, res) => {
    const newMovies = { ...req.body, id: myMovies.length + 1 };
    myMovies.push(newMovies);
    res.status(201).location(`/api/MyMovies/${newMovies.id}`).json(newMovies);
});

// Listen to server on the defined PORT
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
